# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @rdname abc_optim
#' @export
abc_cpp <- function(par, fn, ub = 1e20, lb = -1e20, FoodNumber = 20L, limit = 100L, maxCycle = 1000L, criter = 50L) {
    .Call('ABCoptim_abc_cpp', PACKAGE = 'ABCoptim', par, fn, ub, lb, FoodNumber, limit, maxCycle, criter)
}

