# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.abc_cpp <- function(par, fn, lb, ub, FoodNumber = 20L, limit = 100L, maxCycle = 1000L, criter = 50L) {
    .Call(`_ABCoptim_abc_cpp`, par, fn, lb, ub, FoodNumber, limit, maxCycle, criter)
}

